#ifndef CONNECTIONMANAGEMENTDEFINITIONS_H
#define CONNECTIONMANAGEMENTDEFINITIONS_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

enum ConnectionStatus {
  CONNECTION_STATE_CONNECTING_TO_NETWORK = -1,
  CONNECTION_STATE_DISCONNECTING_FROM_NETWORK = -2,
  CONNECTION_STATE_CHECKING_CONNECTIVITY = -3,
  CONNECTION_STATE_CONNECTING_TO_CLOUD = -4,
  CONNECTION_STATE_DISCONNECTING_FROM_CLOUD = -5,
  CONNECTION_STATUS_DISCONNECTED = 0,
  CONNECTION_STATUS_NETWORK_CONNECTION_ERROR = 1,
  CONNECTION_STATUS_CONNECTED_TO_NETWORK = 2,
  CONNECTION_STATUS_CONNECTIVITY_UNAVAILABLE = 3,
  CONNECTION_STATUS_CONNECTIVITY_AVAILABLE = 4,
  CONNECTION_STATUS_DISCONNECTED_FROM_CLOUD = 5,
  CONNECTION_STATUS_CLOUD_CONNECTION_ERROR = 6,
  CONNECTION_STATUS_CONNECTED_TO_CLOUD = 7
};
typedef enum ConnectionStatus ConnectionStatus_t;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
